feat: merge QDK 2.2.14

diff --git a/QDK_2.2/bin/qbuild b/QDK_2.2/bin/qbuild
--- a/QDK_2.2/bin/qbuild
+++ b/QDK_2.2/bin/qbuild
@@ -49,15 +49,45 @@ check_deprecated_definitions(){
 		QDK_SRC_X19=
 		warn_msg "QDK_SRC_X19: deprecated definition"
 	fi
+        if [ -n "$QDK_SRC_X31" ]; then
+	   [ -z "$QDK_DATA_DIR_X31" ] && QDK_DATA_DIR_X31="$QDK_SRC_X31"
+	   QDK_SRC_X31=
+	   warn_msg "QDK_SRC_X31: deprecated definition"
+	fi
+	if [ -n "$QDK_SRC_X41" ]; then
+           [ -z "$QDK_DATA_DIR_X41" ] && QDK_DATA_DIR_X41="$QDK_SRC_X41"
+           QDK_SRC_X41=
+           warn_msg "QDK_SRC_X41: deprecated definition"
+        fi
 	if [ -n "$QDK_SRC_X86" ]; then
 		[ -z "$QDK_DATA_DIR_X86" ] && QDK_DATA_DIR_X86="$QDK_SRC_X86"
 		QDK_SRC_X86=
 		warn_msg "QDK_SRC_X86: deprecated definition"
 	fi
+	if [ -n "$QDK_SRC_X86_CE53XX" ]; then
+		[ -z "$QDK_DATA_DIR_X86_CE53XX" ] && QDK_DATA_DIR_X86_CE53XX="$QDK_SRC_X86_CE53XX"
+		QDK_SRC_X86_CE53XX=
+		warn_msg "QDK_SRC_X86_CE53XX: deprecated definition"
+	fi
+	if [ -n "$QDK_SRC_X86_BR" ]; then
+		[ -z "$QDK_DATA_DIR_X86_BR" ] && QDK_DATA_DIR_X86_BR="$QDK_SRC_X86_BR"
+		QDK_SRC_X86_BR=
+		warn_msg "QDK_SRC_X86_BR: deprecated definition"
+	fi
+	if [ -n "$QDK_SRC_X86_SB" ]; then
+		[ -z "$QDK_DATA_DIR_X86_SB" ] && QDK_DATA_DIR_X86_SB="$QDK_SRC_X86_SB"
+		QDK_SRC_X86_SB=
+		warn_msg "QDK_SRC_X86_SB: deprecated definition"
+	fi
 	if [ -n "$QDK_SRC_X86_64" ]; then
 		[ -z "$QDK_DATA_DIR_X86_64" ] && QDK_DATA_DIR_X86_64="$QDK_SRC_X86_64"
 		QDK_SRC_X86_64=
 		warn_msg "QDK_SRC_X86_64: deprecated definition"
+	fi
+	if [ -n "$QDK_SRC_X86_64_OMX" ]; then
+		[ -z "$QDK_DATA_DIR_X86_64_OMX" ] && QDK_DATA_DIR_X86_64_OMX="$QDK_SRC_X86_64_OMX"
+		QDK_SRC_X86_64_OMX=
+		warn_msg "QDK_SRC_X86_64_OMX: deprecated definition"
 	fi
 	if [ -n "$QDK_SRC_SHARED" ]; then
 		[ -z "$QDK_DATA_DIR_SHARED" ] && QDK_DATA_DIR_SHARED="$QDK_SRC_SHARED"
@@ -141,7 +171,7 @@ get_qdk_area_pos(){
 	[ -n "$1" ] || err_msg "internal error: get_qdk_area_pos called with no argument"
 	local qpkg="$1"
 	[ -f $qpkg ] || err_msg "$qpkg: no such file"
-	local qdk_area=$(get_content_size $qpkg)
+	local qdk_area="$(get_content_size $qpkg)"
 	local qdk_string="$(/bin/dd if=$qpkg bs=$qdk_area skip=1 2>/dev/null | /bin/dd bs=$QDK_AREA_TAG_LEN count=1 2>/dev/null)"
 	if [ "$qdk_string" = "QDK" ]; then
 		echo "$qdk_area"
@@ -157,7 +187,7 @@ get_qdk_area_data_pos(){
 	local qpkg="$2"
 	[ -f $qpkg ] || err_msg "$qpkg: no such file"
 	local qdk_area=
-	qdk_area=$(get_qdk_area_pos $qpkg) || return 1
+	qdk_area="$(get_qdk_area_pos $qpkg)" || return 1
 	qdk_area=$(($qdk_area + $QDK_AREA_TAG_LEN))
 
 	# Traverse QDK area looking for specified data type. Stop if reaching the end
@@ -175,7 +205,7 @@ get_qdk_area_data_pos(){
 		qdk_pos=$qdk_area
 		qdk_type=$(/usr/bin/hexdump -s $qdk_area -n $QDK_AREA_DATA_TYPE_LEN -e '1/1 "%d"' $qpkg)
 	done
-	if (( $qdk_type == $data_type )); then
+	if [ $qdk_type -eq $data_type ]; then
 		echo "$qdk_pos"
 		return 0
 	fi
@@ -188,7 +218,7 @@ get_signature_pos(){
 	local qpkg="$1"
 	[ -f $qpkg ] || err_msg "$qpkg: no such file"
 	local qdk_pos=
-	qdk_pos=$(get_qdk_area_data_pos $QDK_AREA_SIGNATURE $qpkg) || return 1
+	qdk_pos="$(get_qdk_area_data_pos $QDK_AREA_SIGNATURE $qpkg)" || return 1
 
 	# The signature is located after the data type and size data.
 	echo "$(($qdk_pos + $QDK_AREA_DATA_TYPE_LEN + $QDK_AREA_DATA_SIZE_LEN))"
@@ -200,7 +230,7 @@ get_signature_len(){
 	local qpkg="$1"
 	[ -f $qpkg ] || err_msg "$qpkg: no such file"
 	local qdk_pos=
-	qdk_pos=$(get_qdk_area_data_pos $QDK_AREA_SIGNATURE $qpkg) || return 1
+	qdk_pos="$(get_qdk_area_data_pos $QDK_AREA_SIGNATURE $qpkg)" || return 1
 	qdk_pos=$(($qdk_pos + $QDK_AREA_DATA_TYPE_LEN))
 
 	echo "$(network_order_32bit $qdk_pos $qpkg)"
@@ -253,7 +283,7 @@ is_debug(){
 # Log messages are printed (to stdout) if verbose mode is greater or equal
 # to specified level (default: NORMAL).
 msg(){
-	(( ${2:-$NORMAL} <= $QDK_VERBOSE )) && echo "$1" || return 0
+	[ $QDK_VERBOSE -ge ${2:-$NORMAL} ] && echo "$1" || return 0
 }
 verbose_msg(){
 	msg "$1" $VERBOSE
@@ -400,6 +430,38 @@ add_config_data(){
 	[ -f tmp.$$/conf.tar ] && /bin/gzip -9 tmp.$$/conf.tar
 }
 
+# Add built version to data package directory
+add_built_version(){
+	verbose_msg "Adding built version..."
+
+	local qpkg_built_version=$(/bin/sed -n '/^QPKG_BUILT_VERSION/s/QPKG_BUILT_VERSION="\(.*\)"/\1/p' $QDK_QPKG_CONFIG)
+	if [ "$qpkg_built_version" = "TRUE" ]; then
+		echo -n "time = " > tmp.$$/built_version
+		date "+%Y-%m-%d %H:%M:%S" >> tmp.$$/built_version
+		echo -n "svn = " >> tmp.$$/built_version
+		svn info . | grep Revision | awk '{print $2}' >> tmp.$$/built_version
+	fi
+}
+
+# Add built information to control package directory
+add_built_information(){
+	verbose_msg "Adding built information..."
+
+	echo -n "time = " > build.$$/built_info
+	date "+%Y%m%d" >> build.$$/built_info
+}
+
+#
+perform_data_package_adaptor(){
+	verbose_msg "Adapt the data package files (such as file owner)"
+	if [ -f "../${QDK_DATA_PACKAGE_ADAPTOR}" ]; then
+		echo "Run data package adaptor: ${QDK_DATA_PACKAGE_ADAPTOR}"
+		. ../${QDK_DATA_PACKAGE_ADAPTOR} || err_msg "data package adaptor returned error: $?"
+	elif [ -n "${QDK_DATA_PACKAGE_ADAPTOR}" ]; then
+		warn_msg "${QDK_DATA_PACKAGE_ADAPTOR}: no such file"
+	fi
+}
+
 # Create data package for distribution.
 create_data_package(){
 	local arch_msg="${1:+ for $1}"
@@ -419,6 +481,12 @@ create_data_package(){
 	add_architecture_files "$rsync_opts" "$arch_dir"
 	add_icons
 	add_config_data
+	add_built_version
+
+	# A handler to adapt the data package file (such as file owner)
+	cd build.$$
+	perform_data_package_adaptor
+	cd - > /dev/null 2>&1
 
 	verbose_msg "Creating compressed tar archive..."
 	case "$QDK_COMPRESS_METHOD" in
@@ -457,6 +525,8 @@ create_control_package(){
 
 	/bin/mkdir -m 755 -p build.$$ || err_msg "failed to create directory for control files"
 
+	add_built_information
+
 	/bin/cp -p "$QDK_INSTALL_SCRIPT" build.$$/
 	/bin/cp -p "$QDK_PACKAGE_ROUTINES" build.$$/package_routines
 	/bin/cp -p "$QDK_QPKG_CONFIG" build.$$/qpkg.cfg
@@ -466,6 +536,7 @@ create_control_package(){
     fi
 
 	[ -f tmp.$$/md5sum ] && /bin/cp -p tmp.$$/md5sum build.$$/
+	[ -f tmp.$$/built_version ] && /bin/cp -p tmp.$$/built_version build.$$/
 	[ -f tmp.$$/conf.tar.gz ] && /bin/cp -p tmp.$$/conf.tar.gz build.$$/
 
 	debug_msg "$(/bin/tar -cvzf tmp.$$/${QDK_CONTROL_FILE}.gz -C build.$$ .)"
@@ -506,8 +577,8 @@ pad_field(){
 	eval "field_val=\$$field"
 	local pad_len=$((${2:-10} - ${#field_val}))
 
-	(( 0 <= $pad_len )) || err_msg "the length of $field_val must be less than or equal to ${2:-10}"
-	while (( 0 < $pad_len ))
+	[ $pad_len -ge 0 ] || err_msg "the length of $field_val must be less than or equal to ${2:-10}"
+	while [ $pad_len -gt 0 ]
 	do
 		field_val="$field_val "
 		pad_len=$(($pad_len - 1))
@@ -532,54 +603,84 @@ add_qpkg_header(){
 	case "$arch" in
 		arm-x09)
 			cpu_arch="armv5tejl"
+			reject_platform=
 			;;
 		arm-x19)
 			cpu_arch="armv5tel"
+			reject_platform=
 			;;
+		arm-x31)
+			cpu_arch="armv7l"
+			reject_platform="ARM_AL"
+			;;
+		arm-x41)
+            		cpu_arch="armv7l"
+			reject_platform="ARM_MS"
+            ;;
 		x86)
 			cpu_arch="i.86\|x86_64"
+			reject_platform="X86_EVANSPORT"
+			;;
+		x86_ce53xx)
+			cpu_arch="i686"
+			reject_platform="X86_LAKEPORT\|X86_ATOM"
 			;;
 		x86_64)
 			cpu_arch="x86_64"
+			reject_platform=
 			;;
 		*)
 			cpu_arch=
+			reject_platform=
 			;;
 	esac
 
 	echo "#!/bin/sh" > $QDK_QPKG_FILE
-    /bin/cat >>$QDK_QPKG_FILE <<-EOF
-    find_base(){
-            if [ -z "\$QINSTALL_PATH" ]; then
-                BASE_GROUP="/share/HDA_DATA /share/HDB_DATA /share/HDC_DATA /share/HDD_DATA /share/HDE_DATA /share/HDF_DATA /share/HDG_DATA /share/HDH_DATA /share/HDI_DATA /share/HDJ_DATA /share/HDK_DATA /share/HDL_DATA /share/MD0_DATA /share/MD1_DATA /share/MD2_DATA /share/MD3_DATA"
-                publicdir=\`/sbin/getcfg Public path -f /etc/config/smb.conf\`
-                if [ ! -z \$publicdir ] && [ -d \$publicdir ];then
-                        publicdirp1=\`/bin/echo \$publicdir | /bin/cut -d "/" -f 2\`
-                        publicdirp2=\`/bin/echo \$publicdir | /bin/cut -d "/" -f 3\`
-                        publicdirp3=\`/bin/echo \$publicdir | /bin/cut -d "/" -f 4\`
-                        if [ ! -z \$publicdirp1 ] && [ ! -z \$publicdirp2 ] && [ ! -z \$publicdirp3 ]; then
-                                [ -d "/\${publicdirp1}/\${publicdirp2}/Public" ] && QPKG_BASE="/\${publicdirp1}/\${publicdirp2}"
-                        fi
-                fi
+	/bin/cat >>$QDK_QPKG_FILE <<-EOF
+	find_base(){
+	HDD_MOUNT=\`/sbin/getcfg Public path -f /etc/config/smb.conf\`
+	local log_tool="/sbin/log_tool -t2 -uSystem -p127.0.0.1 -mlocalhost -a"
 
-                # Determine BASE installation location by checking where the Public folder is.
-                if [ -z \$QPKG_BASE ]; then
-                        for datadirtest in \$BASE_GROUP; do
-                        [ -d \$datadirtest/Public ] && QPKG_BASE="/\${publicdirp1}/\${publicdirp2}"
-                        done
-                fi
-                if [ -z \$QPKG_BASE ] ; then
-                        echo "The Public share not found."
-                        return 1
-                fi
-                QPKG_INSTALL_PATH="\${QPKG_BASE}/.qpkg"
-                QPKG_DIR="\${QPKG_INSTALL_PATH}/\${QPKG_NAME}"
-            else
-                QPKG_INSTALL_PATH="\${QINSTALL_PATH}"
-                QPKG_DIR="\${QINSTALL_PATH}/\${QPKG_NAME}"
-            fi
-            return 0
-    }
+	if [ -e "\$HDD_MOUNT" ]; then
+		if [ -z "\$QINSTALL_PATH" ]; then
+	        	BASE_GROUP="/share/HDA_DATA /share/HDB_DATA /share/HDC_DATA /share/HDD_DATA /share/HDE_DATA /share/HDF_DATA /share/HDG_DATA /share/HDH_DATA /share/HDI_DATA /share/HDJ_DATA /share/HDK_DATA /share/HDL_DATA /share/MD0_DATA /share/MD1_DATA /share/MD2_DATA /share/MD3_DATA"
+	        	publicdir=\`/sbin/getcfg Public path -f /etc/config/smb.conf\`
+	        	if [ ! -z \$publicdir ] && [ -d \$publicdir ];then
+	                publicdirp1=\`/bin/echo \$publicdir | /bin/cut -d "/" -f 2\`
+	                publicdirp2=\`/bin/echo \$publicdir | /bin/cut -d "/" -f 3\`
+	                publicdirp3=\`/bin/echo \$publicdir | /bin/cut -d "/" -f 4\`
+	                if [ ! -z \$publicdirp1 ] && [ ! -z \$publicdirp2 ] && [ ! -z \$publicdirp3 ]; then
+	                        [ -d "/\${publicdirp1}/\${publicdirp2}/Public" ] && QPKG_BASE="/\${publicdirp1}/\${publicdirp2}"
+	                fi
+	        fi
+	
+	        # Determine BASE installation location by checking where the Public folder is.
+	        if [ -z \$QPKG_BASE ]; then
+	                for datadirtest in \$BASE_GROUP; do
+	                [ -d \$datadirtest/Public ] && QPKG_BASE="/\${publicdirp1}/\${publicdirp2}"
+	                done
+	        fi
+	        if [ -z \$QPKG_BASE ] ; then
+	                echo "The Public share not found."
+	                return 1
+	        fi
+	        	QPKG_INSTALL_PATH="\${QPKG_BASE}/.qpkg"
+	        	QPKG_DIR="\${QPKG_INSTALL_PATH}/\${QPKG_NAME}"
+		else
+		if [ -e "\$QINSTALL_PATH" ]; then
+                	QPKG_INSTALL_PATH="\${QINSTALL_PATH}"
+                	QPKG_DIR="\${QINSTALL_PATH}/\${QPKG_NAME}"
+		else
+			$log_tool "QTS application install volume not found."
+			exit
+		fi
+             fi
+	        return 0
+	else
+		$log_tool "QTS system volume not found."
+		exit
+	fi
+	}
 	EOF
 
 	if [ -n "$cpu_arch" ]; then
@@ -592,7 +693,11 @@ add_qpkg_header(){
 		}
 		arch_ok(){
 			 local cpu_arch=\$(/bin/uname -m)
-			 [ \$(/usr/bin/expr match "\$cpu_arch" "$cpu_arch") -ne 0 ] || return 1
+			 local reject_platform=\$(/sbin/getcfg "" Platform -f /etc/platform.conf) 
+			if [ \$(/usr/bin/expr match "\$reject_platform" "$reject_platform") == 0 ]; then
+				[ \$(/usr/bin/expr match "\$cpu_arch" "$cpu_arch") -ne 0 ] || return 1
+			else return 1
+			fi
 		}
 		EOF
 	fi
@@ -957,8 +1062,11 @@ assign_defaults(){
 	if [ -z "$QDK_BUILD_ARCH" ]; then
 		is_empty_dir "${QDK_DATA_DIR_X09:-arm-x09}" || add_arch "arm-x09"
 		is_empty_dir "${QDK_DATA_DIR_X19:-arm-x19}" || add_arch "arm-x19"
+		is_empty_dir "${QDK_DATA_DIR_X31:-arm-x31}" || add_arch "arm-x31"
+		is_empty_dir "${QDK_DATA_DIR_X41:-arm-x41}" || add_arch "arm-x41"
 		is_empty_dir "${QDK_DATA_DIR_X86:-x86}" || add_arch "x86"
 		is_empty_dir "${QDK_DATA_DIR_X86_64:-x86_64}" || add_arch "x86_64"
+		is_empty_dir "${QDK_DATA_DIR_X86_CE53XX:-x86_ce53xx}" || add_arch "x86_ce53xx"
 	fi
 	if [ -z "$QDK_BUILD_ARCH" ]; then
 		if [ -f "$QDK_DATA_FILE" ] ||
@@ -996,8 +1104,17 @@ traverse_and_build(){
 			arm-x19)
 				arch_dir="${QDK_DATA_DIR_X19:-arm-x19}"
 				;;
+			arm-x31)
+				arch_dir="${QDK_DATA_DIR_X31:-arm-x31}"
+				;;
+			arm-x41)
+				arch_dir="${QDK_DATA_DIR_X41:-arm-x41}"
+                ;;
 			x86)
 				arch_dir="${QDK_DATA_DIR_X86:-x86}"
+				;;
+			x86_ce53xx)
+				arch_dir="${QDK_DATA_DIR_X86_CE53XX:-x86_ce53xx}"
 				;;
 			x86_64)
 				arch_dir="${QDK_DATA_DIR_X86_64:-x86_64}"
@@ -1274,7 +1391,7 @@ usage(){
 	/bin/cat <<EOF
 usage: $(/usr/bin/basename $0) [--extract QPKG [DIR]] [--create-env NAME] [-s|--section SECTION]
 	[--root ROOT_DIR] [--build-arch ARCH] [--build-version VERSION]
-	[--build-model MODEL] [--build-dir BUILD_DIR] [--force-config]
+	[--build-number NUMBER] [--build-model MODEL] [--build-dir BUILD_DIR] [--force-config]
 	[--setup SCRIPT] [--teardown SCRIPT] [--pre-build SCRIPT]
 	[--post-build SCRIPT] [--exclude PATTERN] [--exclude-from FILE]
 	[--gzip|--bzip2|--7zip|--xz {amd64|armhf}] [--sign] [--gpg-name ID] [--verify QPKG]
@@ -1313,7 +1430,7 @@ usage: $(/usr/bin/basename $0) [--extract QPKG [DIR]] [--create-env NAME] [-s|--
 --build-model MODEL
 	Include check for given model in the QPKG package.
 --build-arch ARCH
-	Build QPKG for specified ARCH (supported values: arm-x09, arm-x19, x86,
+	Build QPKG for specified ARCH (supported values: arm-x09, arm-x19, arm-x31, arm-x41, x86, x86_ce53xx,
 	and x86_64). Only one architecture per option, but you can repeat the
 	option on the command line to add multiple architectures.
 --build-dir BUILD_DIR
@@ -1328,13 +1445,13 @@ usage: $(/usr/bin/basename $0) [--extract QPKG [DIR]] [--create-env NAME] [-s|--
 --pre-build SCRIPT
 	Run specified script before the build process is started. Called before
 	each and every build. First argument contains the architecture (one of
-	arm-x09, arm-x19, x86, and x86_64) and the second argument contains the
+	arm-x09, arm-x19, arm-x31, arm-x41,x86, x86_ce53xx, and x86_64) and the second argument contains the
 	location of the architecture specific code. For the generic build the
 	arguments are empty.
 --post-build SCRIPT
 	Run specified script after the build process is finished. Called after
 	each and every build. First argument contains the architecture (one of
-	arm-x09, arm-x19, x86, and x86_64) and the second argument contains the
+	arm-x09, arm-x19, arm-x31, arm-x41, x86, x86_ce53xx, and x86_64) and the second argument contains the
 	location of the architecture specific code. For the generic build the
 	arguments are empty.
 --create-env NAME
@@ -1441,7 +1558,7 @@ main(){
 	local qbuild_add_sign_file=
 	local qbuild_sign=
 	local qbuild_list_keys=
-	while  (( 0 < $# ))
+	while  [ $# -gt 0 ]
 	do
 		case "$1" in
 		--usage)	qbuild_usage=TRUE ;;
@@ -1498,6 +1615,9 @@ main(){
 				[ -n "$arch" ] || err_msg "--build-arch: no architecture"
 				add_arch "$arch"
 				shift
+				if [ -f qinstall-$arch.sh ]; then
+					cp -af qinstall-$arch.sh qinstall.sh
+				fi
 				;;
 		--build-model)	QDK_BUILD_MODEL="$2"
 				[ -n "$QDK_BUILD_MODEL" ] || err_msg "--build-model: no model"
